import 'package:flutter/material.dart';
import 'config_service.dart';
import 'device_config.dart';

/// Shown on first launch (no saved config). The cashier enters:
///   1. The Laravel server URL (e.g. https://withqash-demo.tech) — the
///      central domain, NOT the tenant subdomain; activation returns the
///      tenant's own api_base_url.
///   2. The 12-char activation token generated by `device:token` artisan command
class SetupScreen extends StatefulWidget {
  final void Function(DeviceConfig config) onActivated;

  const SetupScreen({super.key, required this.onActivated});

  @override
  State<SetupScreen> createState() => _SetupScreenState();
}

class _SetupScreenState extends State<SetupScreen> {
  final _formKey = GlobalKey<FormState>();
  final _urlController = TextEditingController(text: 'https://');
  final _tokenController = TextEditingController();
  bool _loading = false;
  String? _error;

  Future<void> _activate() async {
    if (!_formKey.currentState!.validate()) return;
    setState(() { _loading = true; _error = null; });
    try {
      final config = await ConfigService.activate(
        _urlController.text.trim().replaceAll(RegExp(r'/$'), ''),
        _tokenController.text,
      );
      widget.onActivated(config);
    } catch (e) {
      setState(() => _error = e.toString().replaceFirst('Exception: ', ''));
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  @override
  void dispose() {
    _urlController.dispose();
    _tokenController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Device Setup')),
      body: Center(
        child: ConstrainedBox(
          constraints: const BoxConstraints(maxWidth: 400),
          child: Padding(
            padding: const EdgeInsets.all(24),
            child: Form(
              key: _formKey,
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  const Icon(Icons.print, size: 64),
                  const SizedBox(height: 24),
                  Text(
                    'Print Station Setup',
                    style: Theme.of(context).textTheme.headlineSmall,
                    textAlign: TextAlign.center,
                  ),
                  const SizedBox(height: 8),
                  Text(
                    'Enter the server URL and the activation token\nprovided by your administrator.',
                    style: Theme.of(context).textTheme.bodyMedium,
                    textAlign: TextAlign.center,
                  ),
                  const SizedBox(height: 32),
                  TextFormField(
                    controller: _urlController,
                    decoration: const InputDecoration(
                      labelText: 'Server URL',
                      hintText: 'https://withqash-demo.tech',
                      border: OutlineInputBorder(),
                    ),
                    keyboardType: TextInputType.url,
                    autocorrect: false,
                    validator: (v) {
                      final uri = Uri.tryParse((v ?? '').trim());
                      if (uri == null ||
                          !(uri.isScheme('http') || uri.isScheme('https')) ||
                          uri.host.isEmpty) {
                        return 'Enter a full URL, e.g. https://withqash-demo.tech';
                      }
                      return null;
                    },
                  ),
                  const SizedBox(height: 16),
                  TextFormField(
                    controller: _tokenController,
                    decoration: const InputDecoration(
                      labelText: 'Activation Token',
                      hintText: 'XXXXXXXXXXXX (12 characters)',
                      border: OutlineInputBorder(),
                    ),
                    autocorrect: false,
                    textCapitalization: TextCapitalization.characters,
                    maxLength: 12,
                    validator: (v) {
                      if (v == null || v.trim().length != 12) return 'Must be exactly 12 characters';
                      return null;
                    },
                  ),
                  if (_error != null) ...[
                    const SizedBox(height: 8),
                    Text(_error!, style: TextStyle(color: Theme.of(context).colorScheme.error)),
                  ],
                  const SizedBox(height: 16),
                  FilledButton(
                    onPressed: _loading ? null : _activate,
                    child: _loading
                        ? const SizedBox(height: 20, width: 20, child: CircularProgressIndicator(strokeWidth: 2))
                        : const Text('Activate'),
                  ),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}
